name: CI

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
          submodules: true

    # Runs a set of commands using the runners shell
    - name: Install dependencies
      run: |
        sudo bash -c 'source /etc/lsb-release && echo "
          deb [arch=amd64] http://us.archive.ubuntu.com/ubuntu ${DISTRIB_CODENAME} main universe
          deb [arch=amd64] http://us.archive.ubuntu.com/ubuntu ${DISTRIB_CODENAME}-updates main universe
          deb [arch=amd64] http://us.archive.ubuntu.com/ubuntu ${DISTRIB_CODENAME}-backports main universe
          " > /etc/apt/sources.list'
          sudo rm -Rf /etc/apt/sources.list.d
          sudo apt-get update -m
          
        sudo apt-get install \
         libsdl2-dev \
         libsdl2-image-dev \
         libsdl2-ttf-dev \
         libx11-dev:amd64 \
         libxtst-dev:amd64 \
         libxt-dev:amd64 \
         libxinerama-dev \
         libx11-xcb-dev \
         libxkbcommon-dev \
         libxkbcommon-x11-dev \
         libxkbfile-dev
         
    - name: Compile
      shell: bash
      run: | # TODO: obs-studio plugin build
          cmake -S ${{github.workspace}} -B ${{github.workspace}}/build \
            -G "Unix Makefiles" \
            -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/dist \
            -DCMAKE_VERBOSE_MAKEFILE=true -DENABLE_PLUGIN=OFF
          cmake --build ${{github.workspace}}/build \
            --parallel 2 \
            --target install
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
          name: linux-ubuntu
          path: ${{github.workspace}}/dist/**/*
